### ISSUE TITLE
Cannot add an entry in empty database

### ISSUE THREAD

**Issue by elbotho** [kartevonmorgen/openfairdb#112]
I have a problem setting openfairdb up:
I had to build it myself (mac) and everything seemed ok (some warnings) but I can't find any content in the frontend.
when running `./openfairdb` it starts, but with an error:
```
ERROR 2018-10-24T13:11:49Z: rocket::rocket: 🚀  Rocket has launched from http://127.0.0.1:6767
```

Any ideas?

**Comment by david-ziegler** [comment]
that's the standard behaviour. It's not actually an error. I don't know why rocket log this as 'error'. My guess is that if they used another log-level you wouldn't usually see it...
So, openfairdb should be working fine when you see this!

**Comment by elbotho** [comment]
Thanks for the promt answer!
Is there usually some content that I can find using the fronend? 
Or can I import some?

Currently I can only find places (nothing from the db) and trying to create an entry results in
`app.js:82487 POST http://0.0.0.0:8080/api/entries/ 500 (Internal Server Error)`

**Comment by david-ziegler** [comment]
on the first startup there is an empty database. That's also why you get the error because in order to create an entry it must be assigned to one of the categories (in our frontend kartevonmorgen.org that's "project"/"company"/"event". But in the beginning you don't have any categories in the database.
So, the very first time you need to add some categories manually with a tool like https://sqlitebrowser.org/ Sorry for the inconvenience! This software has been developed for a large part by volunteers, so it's not perfect yet. Feel free to contribute and open a pull request.

On another note: what are you planning to use openfairdb for? I'm just interested. :)

**Comment by elbotho** [comment]
So I basically just have to add the categories in the db manually?
Like this?
![image](https://user-images.githubusercontent.com/1258870/47441645-dc988880-d7b0-11e8-875a-2c783fb3e929.png)
still no luck.
Could you provide me with your db file or some sql I could run?

(edit: Ah yes, I just try to get the "local development setup" of the Karte von morgen running)

**Comment by david-ziegler** [comment]
here is an example database with some example data. This one works.
[openfair.db.zip](https://github.com/flosse/openfairdb/files/2511314/openfair.db.zip)

> (edit: Ah yes, I just try to get the "local development setup" of the Karte von morgen running)

Nice! are you planning to make some changes/contribute? And who are you? :) :)

**Comment by uklotzde** [comment]
As David mentioned you need to use the exact category IDs that are currently hard-coded in the _kartevonmorgen_ code for initializing _openfairdb_. Those IDs are strings, not simple integer numbers:

|id|name|
|---|---|
|2cd00bebec0c48ba9db761da48678134|initiative|
|77b3c33a92554bcf8e8c2c86cedd6f6f|company|

**Comment by elbotho** [comment]
@ziedavid  Thank you very much, it works now!
Is there some piece of information that I overlooked, or should we add this somewhere in the readmes?
(I guess most people come here from kartevonmorgen, right?)

Or could I also set the fronend up to use the osdb api remotely?


> Nice! are you planning to make some changes/contribute? And who are you? :) :)

Definite maybe, still scouting. can tell you more next week 👍 
I'm with a designer / fe-dev with [Transition München](https://transition-muc.de/) and [Serlo](https://serlo.org).

**Comment by david-ziegler** [comment]
yes, and in the long run this shouldn't be hardcoded anymore. but yes, for now it would be good to mention it in the README...

> I'm with a designer / fe-dev with [Transition München](https://transition-muc.de/) and [Serlo](https://serlo.org).

ah nice! :)

**Comment by elbotho** [comment]
Ping @ziedavid @flosse 
(this mostly concerns [kartevonmorgen](https://github.com/flosse/kartevonmorgen))
Ok it's decided! We will build the prototype (at least) of our transition-muc map on KvM.
Working with it has been great so far! 👍 

My current plan is to make some changes (mostly design/UI) in [my fork](https://github.com/elbotho/kartevonmorgen) and you/the team can decide what features or changes you want to pull. I think most of them will be good for the whole project (e.g. I build clickable tags yesterday) but maybe not the small design changes.
I will also work on some existing issues.
Current demo of the fork is here: https://elbotho.github.io/kartevonmorgen/docs
Sounds good for you? Any wishes?
How do you communicate currently?

**Comment by david-ziegler** [comment]
awesome 👍 
I like the clickable tags, we'll definitely pull them. And yes I also see a lot of possible improvements design-wise. I'm curious to see what you'll do there.

Let's have a call sometime! To see how to work together and to coordinate further development. For example one thing I'm not yet decided about is how to do styling: we have a huge stylus-stylesheet but I gradually moved with some components to `styled-components` which made it more modular/flexible to reuse components. But I'm happy to discuss alternatives. Just as an example.
What's your number? Mine is: 01577 680 1234. I have time tomorrow for example.

We communicate via: 
- most importantly Github. The kartevonmorgen repository is kind of our main repository, which contains overall issues of the project that sometimes might also be openfairdb issues. For example I use this Kanban board for prioritization and tracking of issues: https://github.com/flosse/kartevonmorgen/projects/5 This as an overview, but when it comes to implementation we create openfairdb-issues in the openfairdb-repository.
- phone: I always find a phone call more efficient than writing emails back and forth
- we have a Karte von morgen mailing list for the whole team. Are you interested to join?
- Trello: mostly Helmut is using Trello to organize all kind of information like funding applications, education projects, future features etc.

**Comment by wellemut** [comment]
@elbotho mega cool! Das freut uns riesig und ich bin begeistert wie schnell hier plötzlich manches Wirklichkeit wird!

Also herzlich willkommen im Team!

Besonders am Handy finde ich die größeren Punkte sehr angenehm. Auch die schlichtere Hintergrundkarte macht es auch schon viel übersichtlicher. (Auch wenn sie etwas arg farblos ist) Wirklich stören tut mich jedoch, dass ich nicht mehr ganz raus zoomen kann.

**Comment by elbotho** [comment]
@wellemut thank you very much for your kind words! 
The zoom-restriction was just a test, don't worry :)
